-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 25, 2025 at 05:05 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `travelworldweb`
--

-- --------------------------------------------------------

--
-- Table structure for table `bookings`
--

CREATE TABLE `bookings` (
  `booking_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `tour_id` int(11) NOT NULL,
  `people` int(11) NOT NULL,
  `checkin` date NOT NULL,
  `checkout` date NOT NULL,
  `total_price` decimal(10,2) DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `payment_method` varchar(50) DEFAULT NULL,
  `ticket_type` varchar(50) DEFAULT NULL,
  `discount_code` varchar(50) DEFAULT NULL,
  `services` text DEFAULT NULL,
  `remaining_price` decimal(10,2) DEFAULT 0.00,
  `deposit` decimal(10,2) DEFAULT 0.00,
  `status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0: Mới, 1: Đã xác nhận, 2: Đã hoàn thành, 3: Đã hủy'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `bookings`
--

INSERT INTO `bookings` (`booking_id`, `user_id`, `tour_id`, `people`, `checkin`, `checkout`, `total_price`, `name`, `email`, `phone`, `note`, `payment_method`, `ticket_type`, `discount_code`, `services`, `remaining_price`, `deposit`, `status`) VALUES
(1111, 137, 6, 1, '2025-06-19', '2025-06-24', 70000000.00, 'Dang Phan', 'haidangphan053@gmail.com', '0889013678', '34t453ert45y', 'credit-card', 'maybay', '32r4t4gy4', 'insurance', 68758000.00, 1242000.00, 2),
(1112, 137, 8, 1, '2025-06-16', '2025-06-19', 5000000.00, 'Thanh Nguyen', 'haidangphan053@gmail.com', '0889013678', '', 'bank', 'maybay', '', 'insurance', 3000000.00, 2000000.00, 3),
(1113, 137, 13, 1, '2025-06-16', '2025-06-19', 7000000.00, 'Nguyen Le', 'haidangphan053@gmail.com', '0889013678', '', 'bank', 'maybay', '', 'insurance', 5000000.00, 2000000.00, 2),
(1114, 137, 13, 1, '2025-06-16', '2025-06-19', 7000000.00, 'Le Tuan', 'haidangphan053@gmail.com', '0889013678', '', 'bank', 'maybay', '', 'insurance', 5000000.00, 2000000.00, 1),
(1115, 137, 20, 1, '2025-06-16', '2025-06-21', 18000000.00, 'Nguyen Thi Phat', 'haidangphan053@gmail.com', '0889013678', '', 'bank', 'maybay', '', 'insurance', 16000000.00, 2000000.00, 0),
(1116, 138, 3, 1, '2222-01-02', '2222-01-05', 7000000.00, '1', 'user@1', '1', '1', 'bank', 'xekhach', '1', 'insurance', 6000000.00, 1000000.00, 0);

-- --------------------------------------------------------

--
-- Table structure for table `contacts`
--

CREATE TABLE `contacts` (
  `contact_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `message` text DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `destinations`
--

CREATE TABLE `destinations` (
  `destination_id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `section_1` text DEFAULT NULL COMMENT 'caption||image.jpg;;caption2||image2.jpg',
  `section_2` text DEFAULT NULL COMMENT 'caption||image.jpg;;caption2||image2.jpg',
  `best_time_to_visit` varchar(255) DEFAULT NULL,
  `map_embed` text DEFAULT NULL,
  `image_gallery` text DEFAULT NULL,
  `slug` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `destinations`
--

INSERT INTO `destinations` (`destination_id`, `name`, `country`, `description`, `image_url`, `section_1`, `section_2`, `best_time_to_visit`, `map_embed`, `image_gallery`, `slug`) VALUES
(1, 'Vịnh Hạ Long', 'Việt Nam', 'Nằm ở tỉnh Quảng Ninh, Vịnh Hạ Long là một trong những kỳ quan thiên nhiên thế giới được UNESCO công nhận. Với hàng nghìn hòn đảo đá vôi kỳ vĩ, hang động huyền bí và mặt nước trong xanh như ngọc, nơi đây là điểm đến không thể bỏ lỡ cho những ai yêu thích vẻ đẹp thơ mộng và hùng vĩ của thiên nhiên. Hãy thử một chuyến du thuyền ngủ đêm để cảm nhận vẻ yên bình hiếm có giữa lòng biển trời miền Bắc.', 'https://vcdn1-dulich.vnecdn.net/2023/07/12/HL1-9875-1689130357.jpg?w=0&h=0&q=100&dpr=1&fit=crop&s=mN2YMaNq5Vgj_oi6A_s91Q', 'Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no', 'Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no;;Hang Đầu Gỗ||https://lh3.googleusercontent.com/p/AF1QipNPOOju-mlc66_7O5nCN0F5LlxdMpirn_rM7QkM=s294-w294-h220-n-k-no', '5/18/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=V%E1%BB%8Bnh+H%E1%BA%A1+Long&output=embed\"></iframe></div><a href=\"https://viralnado.net/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">viralnado.net</a></div>', 'https://special.nhandan.vn/30-nam-mot-chang-duong-di-san-Vinh-Ha-Long/assets/HLCklusX0n/things-to-do-in-ha-long-bay-banner-1-1920x1080.jpg', 'vinh-ha-long'),
(2, 'Côn Đảo', 'Việt Nam', 'Côn Đảo không chỉ nổi tiếng với những bãi biển nguyên sơ, làn nước trong vắt và hệ sinh thái phong phú, mà còn là nơi ghi dấu lịch sử dân tộc với hệ thống nhà tù Côn Đảo. Một nơi vừa để nghỉ dưỡng, vừa để lắng đọng và tưởng nhớ, Côn Đảo mang lại trải nghiệm trọn vẹn cả về thiên nhiên lẫn tinh thần.', 'https://media-cdn.tripadvisor.com/media/photo-s/29/b5/44/c4/six-senses-con-dao.jpg', '', '', '7/10/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=C%C3%B4n+%C4%90%E1%BA%A3o&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://vlink.vn/wp-content/uploads/2024/12/589-con-dao-tu-dia-nguc-tran-gian-den-thien-duong-du-l.jpg', 'con-dao'),
(3, 'Đà Nẵng - Hội An', 'Việt Nam', 'Đà Nẵng sôi động với bãi biển Mỹ Khê, bán đảo Sơn Trà và cầu Rồng hiện đại, trong khi Hội An lại níu chân du khách bởi những mái nhà cổ kính, đèn lồng rực rỡ và dòng sông Hoài thơ mộng. Cặp đôi \"vàng\" của miền Trung này là điểm đến lý tưởng cho mọi loại hình du lịch – từ nghỉ dưỡng, khám phá văn hóa đến ẩm thực đặc sắc.', 'https://i2.ex-cdn.com/crystalbay.com/files/content/2024/11/01/di-da-nang-hoi-an-nen-di-may-ngay-3-0926.jpg', '', '', '5/6/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=%C4%90%C3%A0+N%E1%BA%B5ng+-+H%E1%BB%99i+An&output=embed\"></iframe></div><a href=\"https://testosteronetherapy.org/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">testosteronetherapy.org</a></div>', 'https://i2.ex-cdn.com/crystalbay.com/files/content/2024/11/01/di-da-nang-hoi-an-nen-di-may-ngay-3-0926.jpg', 'da-nang-hoi-an'),
(4, 'Cố đô Huế', 'Việt Nam', 'Huế – mảnh đất cố đô yên bình với hệ thống lăng tẩm, đền đài và kiến trúc cung đình triều Nguyễn được UNESCO công nhận là Di sản Văn hóa Thế giới. Không gian thơ mộng bên dòng sông Hương, tiếng chuông chùa Thiên Mụ vang vọng, và ẩm thực cung đình tinh tế khiến mỗi bước chân đến Huế đều là một chuyến trở về quá khứ đầy cảm xúc.', 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Ngomon2.jpg', '', '', '5/27/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=C%E1%BB%91+%C4%91%C3%B4+Hu%E1%BA%BF&output=embed\"></iframe></div><a href=\"https://aitohumanizetextconverter.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aitohumanizetextconverter.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYFx_SH1i1iMsYoj5w6hAgnVDooW555nObj7sGaAVBfQ&s&ec=72940543', 'co-do-hue'),
(5, 'Phú Quốc', 'Việt Nam', 'Với biển xanh cát trắng, những khu nghỉ dưỡng sang trọng và hệ sinh thái biển phong phú, Phú Quốc là thiên đường nghỉ dưỡng đúng nghĩa. Bạn có thể khám phá Nam đảo với cáp treo Hòn Thơm, tắm biển tại Bãi Sao, thưởng thức hải sản tươi sống hoặc dạo chơi trong các khu vui chơi giải trí hàng đầu như VinWonders hay Grand World.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjZWhRT0vwzWahfmPQgwKG7Cf05jaEurlPcQ&s', '', '', '5/3/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Ph%C3%BA+Qu%E1%BB%91c&output=embed\"></iframe></div><a href=\"https://freeairecipegenerator.com\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">freeairecipegenerator.com</a></div>', 'https://cdn.xanhsm.com/2025/02/9fce97ed-phu-quoc-thuoc-tinh-nao-1.jpg', 'phu-quoc'),
(6, 'Hang Sơn Đoòng', 'Việt Nam', 'Nằm trong Vườn quốc gia Phong Nha – Kẻ Bàng (Quảng Bình), Hang Sơn Đoòng là hang động tự nhiên lớn nhất hành tinh, với hệ sinh thái riêng biệt, rừng nguyên sinh và cả sông ngầm bên trong. Đây là điểm đến mơ ước của những tín đồ phiêu lưu mạo hiểm. Trải nghiệm trekking vào lòng hang là hành trình đầy thử thách nhưng mang lại cảm giác chinh phục vô cùng xứng đáng.', 'https://thanhnien.mediacdn.vn/Uploaded/phucndh/2022_04_14/a4-5211.jpg', '', '', '6/3/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Hang+S%C6%A1n+%C4%90o%C3%B2ng&output=embed\"></iframe></div><a href=\"https://www.ohiovalleyeats.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">ohiovalleyeats.com</a></div>', 'https://gcs.tripi.vn/public-tripi/tripi-feed/img/482754PxI/anh-mo-ta.png', 'hang-son-doong'),
(7, 'Ninh Bình', 'Việt Nam', 'Với phong cảnh \"non nước hữu tình\", Ninh Bình là điểm đến nổi bật ở miền Bắc với quần thể danh thắng Tràng An – Di sản văn hóa và thiên nhiên thế giới. Bạn sẽ được ngồi thuyền xuyên qua các hang động kỳ ảo, khám phá cố đô Hoa Lư cổ kính, và chiêm ngưỡng vẻ đẹp hùng vĩ tại Tam Cốc – Bích Động hay Hang Múa. Một bức tranh sơn thủy hữu tình giữa đời thực.', 'https://thungnham.com/wp-content/uploads/2024/03/khu-du-lich-trang-an-2.webp', '', '', '7/1/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Ninh+B%C3%ACnh&output=embed\"></iframe></div><a href=\"https://mapembeds.com\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">mapembeds.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSk1501ImPtvYDxqNBPVzkgrIf6Sc6bZfvBHPzhDi8Csg&s&ec=72940543', 'ninh-binh'),
(8, 'Bãi Cát Bà', 'Việt Nam', 'Thuộc thành phố Hải Phòng, quần đảo Cát Bà sở hữu những bãi biển hoang sơ, làn nước trong vắt và vườn quốc gia xanh mướt. Du khách có thể kết hợp nghỉ dưỡng biển và khám phá thiên nhiên hoang dã, chèo kayak, leo núi đá hoặc thăm các làng chài ven biển. Cát Bà cũng là cửa ngõ lý tưởng để khám phá vịnh Lan Hạ – một “phiên bản” yên tĩnh và lãng mạn hơn của vịnh Hạ Long.', 'https://catbaexpress.com/upload/images/bai_bien_cat_co_cat_ba.jpg', '', '', '4/23/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=B%C3%A3i+C%C3%A1t+B%C3%A0&output=embed\"></iframe></div><a href=\"https://viralnado.net/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">viralnado.net</a></div>', 'https://catba.net.vn/wp-content/uploads/2024/06/bien-cat-ba1.jpg', 'bai-cat-ba'),
(9, 'Thác Bản Giốc', 'Việt Nam', 'Nằm tại biên giới Việt – Trung, thác Bản Giốc (Cao Bằng) là một trong những thác nước lớn và đẹp nhất châu Á. Nước chảy cuồn cuộn từ độ cao hàng chục mét xuống lòng suối tạo nên khung cảnh ngoạn mục giữa núi rừng xanh mướt. Đây là điểm đến lý tưởng cho những ai yêu thiên nhiên, nhiếp ảnh và muốn khám phá vẻ đẹp hùng vĩ của vùng cao Đông Bắc.', 'https://hanotour.com.vn/upload_images/images/thac_B%E1%BA%A3n_Gi%E1%BB%91c.jpg', '', '', '6/5/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Th%C3%A1c+B%E1%BA%A3n+Gi%E1%BB%91c&output=embed\"></iframe></div><a href=\"https://eatcolumbus.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">eatcolumbus.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxe4LnpIdbY0ZAACoHkUEcRkXw0bVClvLb0eg3oufK7Q&s&ec=72940543', 'thac-ban-gioc'),
(10, 'Tháp Bánh Ít', 'Việt Nam', 'Tọa lạc trên một ngọn đồi cao tại Bình Định, Tháp Bánh Ít là cụm tháp Chăm cổ mang đậm dấu ấn kiến trúc Hindu giáo, có niên đại từ thế kỷ XI. Với lối kiến trúc độc đáo, các chi tiết điêu khắc tinh xảo và khung cảnh thiên nhiên bao quanh yên bình, nơi đây như một viên ngọc trầm mặc của miền đất võ. Đây cũng là điểm check-in ấn tượng với tầm nhìn toàn cảnh tuyệt đẹp.', 'https://binhdinh.gov.vn/upload/3005784/20220516/thap-banh-it-thap-chinh_79cc8_20eb8.jpg', '', '', '6/8/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Th%C3%A1p+B%C3%A1nh+%C3%8Dt&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR22DaW88B_mAEs4KLimgpjO4Jn6Z9AIHUwjN39eax9BA&s&ec=72940543', 'thap-banh-it'),
(11, 'Siem Reap', 'Campuchia', 'Siem Reap là cửa ngõ dẫn vào quần thể đền đài Angkor nổi tiếng, với điểm nhấn là Angkor Wat – kỳ quan kiến trúc tôn giáo lớn nhất thế giới. Ngoài những công trình cổ kính phủ đầy rêu phong, du khách còn có thể trải nghiệm nền văn hóa Khmer độc đáo, thưởng thức ẩm thực đường phố và chiêm ngưỡng cảnh bình minh ngoạn mục trên nền đền cổ.', 'https://www.siemreap.net/wp-content/uploads/2017/12/siem-reap-pub-street-sunset.jpg', '', '', '6/27/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Siem+Reap&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://www.experienceparkhyattsiemreap.com/wp-content/uploads/2023/05/Park-Hyatt-Siem-Reap-SEO-MAY-C01-2.jpg', 'siem-reap'),
(12, 'Vạn Lý Trường Thành', 'Trung Quốc', 'Trải dài hàng ngàn km qua núi non trùng điệp, Vạn Lý Trường Thành là kỳ quan do con người xây dựng có thể nhìn thấy từ không gian. Đây không chỉ là một công trình quân sự vĩ đại, mà còn là minh chứng cho trí tuệ và sức mạnh của nền văn minh Trung Hoa. Những đoạn tường thành tại Badaling hay Jinshanling là nơi lý tưởng để du khách khám phá và chụp ảnh.', 'https://transviet.com.vn/images/Khuyen-Mai/Avatar/cam_nang_du_lich/great-wall-transviet3.png', '', '', '5/6/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=V%E1%BA%A1n+L%C3%BD+Tr%C6%B0%E1%BB%9Dng+Th%C3%A0nh&output=embed\"></iframe></div><a href=\"http://aiyoutubetitlegenerator.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aiyoutubetitlegenerator.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUjqvBRtEFvvEdZGw5SrdMnHiqSquGN_VqpsgCeHZBPg&s&ec=72940543', 'van-ly-truong-thanh'),
(13, 'Kuala Lumpur', 'Malaysia', 'Thủ đô Malaysia là nơi hội tụ của nhiều nền văn hóa: Mã Lai, Trung Hoa, Ấn Độ… Tòa tháp đôi Petronas lừng danh, các khu mua sắm sầm uất, ẩm thực đường phố đa dạng và những đền chùa mang đậm bản sắc bản địa khiến Kuala Lumpur trở thành điểm đến lý tưởng cho những ai yêu thích sự hiện đại xen lẫn truyền thống.', 'https://lp-cms-production.imgix.net/2022-11/Malaysia-iStock-1344146598-RFE_1.jpeg?w=1095&fit=crop&crop=faces%2Cedges&auto=format&q=75', '', '', '7/9/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Kuala+Lumpur&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://digital.ihg.com/is/image/ihg/crowne-plaza-kuala-lumpur-9304098596-2x1', 'kuala-lumpur'),
(14, 'Đền Taj Mahal', 'Ấn Độ', 'Nằm ở thành phố Agra (Ấn Độ), Taj Mahal là một trong bảy kỳ quan thế giới mới, được xây dựng như một biểu tượng của tình yêu vĩnh cửu. Kiến trúc tuyệt mỹ với cẩm thạch trắng tinh khôi, kết hợp hài hòa giữa phong cách Ba Tư, Thổ Nhĩ Kỳ và Ấn Độ, khiến nơi đây trở thành điểm đến không thể bỏ qua khi đến Nam Á.', 'https://mia.vn/media/uploads/blog-du-lich/di-tich-den-taj-mahal-an-do-02-1702374379.jpg', '', '', '4/25/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=%C4%90%E1%BB%81n+Taj+Mahal&output=embed\"></iframe></div><a href=\"https://eatcolumbus.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">eatcolumbus.com</a></div>', 'https://media-cdn-v2.laodong.vn/Storage/NewsPortal/2019/5/22/735026/11.jpg', 'den-taj-mahal'),
(15, 'Đảo Bali', 'Indonesia', 'Bali là điểm đến mơ ước của hàng triệu du khách nhờ những bãi biển quyến rũ, ruộng bậc thang Ubud xanh mát, các đền chùa linh thiêng và nền văn hóa Hindu độc đáo. Đây là nơi hoàn hảo cho mọi kiểu du lịch: từ lướt sóng, yoga, tiệc tùng cho đến những chuyến nghỉ dưỡng yên bình.', 'https://booking.pystravel.vn/uploads/posts/albums/5053/88c7a9338a57e980a3794612b8e6793f.jpg', '', '', '5/25/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=%C4%90%E1%BA%A3o+Bali&output=embed\"></iframe></div><a href=\"https://eatcolumbus.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">eatcolumbus.com</a></div>', 'https://ik.imagekit.io/tvlk/blog/2022/12/dia-diem-du-lich-bali-1.jpg?tr=q-70,c-at_max,w-500,h-300,dpr-2', 'dao-bali'),
(16, 'Chùa Shwedagon', 'Myanmar', 'Toạ lạc tại Yangon, chùa Shwedagon là ngôi chùa vàng nổi tiếng nhất Myanmar, được dát hàng tấn vàng thật và đính hàng ngàn viên đá quý. Nơi đây không chỉ là địa điểm hành hương tôn giáo mà còn là điểm tham quan văn hoá không thể bỏ lỡ, đặc biệt là vào lúc hoàng hôn khi toàn bộ ngôi chùa rực sáng trong ánh vàng óng ả.', 'https://media.tuyenquangtv.vn/public/file/fb9e3a036ab59c2c016ac3618a0d3aec/old_image/uploaded/130/2017/1/4/030_chua-shwedagon-1.jpg', '', '', '7/9/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Ch%C3%B9a+Shwedagon&output=embed\"></iframe></div><a href=\"https://aitohumanizetextconverter.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aitohumanizetextconverter.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYT8kxqLpHR7oLoUgicg6PTP2LTIYJq9Hcmz4U8NGSPA&s&ec=72940543', 'chua-shwedagon'),
(17, 'Bangkok', 'Thái Lan', 'Thủ đô Thái Lan là một tổ hợp sôi động giữa truyền thống và hiện đại. Từ những ngôi chùa vàng lấp lánh như Wat Arun, Wat Pho, đến các khu chợ đêm, trung tâm mua sắm, phố Khao San nhộn nhịp và thiên đường ẩm thực đường phố, Bangkok luôn làm hài lòng mọi du khách.', 'https://static.independent.co.uk/2025/01/03/14/newFile-12.jpg', '', '', '4/27/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Bangkok&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://static.independent.co.uk/2025/01/03/14/newFile-12.jpg', 'bangkok'),
(18, 'Thượng Hải - Bắc Kinh', 'Trung Quốc', 'Nếu Thượng Hải gây ấn tượng với những toà nhà chọc trời, phố đi bộ Nam Kinh và bến Thượng Hải hoa lệ, thì Bắc Kinh lại đưa bạn trở về với lịch sử hàng nghìn năm tại Tử Cấm Thành, Thiên An Môn, và Di Hòa Viên. Kết hợp cả hai thành phố sẽ mang lại bức tranh toàn cảnh về một Trung Hoa vừa truyền thống vừa hiện đại.', 'https://cdn.saigontimestravel.com/storage/images/retail/wp-content/uploads/2024/02/Tour-Bac-Kinh-10.jpg', '', '', '6/20/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Th%C6%B0%E1%BB%A3ng+H%E1%BA%A3i+-+B%E1%BA%AFc+Kinh&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://achautravel.com/upload/images/1562048068-product-slide-2.jpeg', 'thuong-hai-bac-kinh'),
(19, 'Seoul', 'Hàn Quốc', 'Thủ đô của Hàn Quốc là một điểm đến hấp dẫn với sự giao thoa tuyệt vời giữa cổ kính và hiện đại. Bạn có thể tham quan cung điện Gyeongbokgung, mua sắm ở Myeongdong, dạo chơi Hongdae sôi động về đêm, hoặc khám phá các làng cổ như Bukchon Hanok để cảm nhận rõ nhịp sống Hàn Quốc đương đại.', 'https://static.independent.co.uk/2022/12/29/14/iStock-464629385.jpg?width=1200&height=900&fit=crop', '', '', '5/15/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Seoul&output=embed\"></iframe></div><a href=\"https://viralnado.net/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">viralnado.net</a></div>', 'https://icoeuro.vn/vnt_upload/location/2_23.png', 'seoul'),
(20, 'Tokyo', 'Nhật Bản', 'Tokyo là nơi bạn có thể tìm thấy mọi thứ: từ đền Meiji thanh tịnh đến khu Shibuya sôi động; từ công nghệ tiên tiến đến văn hóa truyền thống sâu sắc. Thưởng thức sushi tươi sống, tham quan tháp Tokyo, hoặc đắm mình trong thế giới anime tại Akihabara – thủ đô Nhật Bản luôn khiến du khách bất ngờ và choáng ngợp.', 'https://plus.unsplash.com/premium_photo-1661914240950-b0124f20a5c1?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dG9reW98ZW58MHx8MHx8fDA%3D', '', '', '6/28/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Tokyo&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://danso.info/wp-content/uploads/2025/03/Tokyo-scaled.jpg', 'tokyo'),
(21, 'Paris', 'Pháp', 'Paris là điểm đến mơ ước với biểu tượng là tháp Eiffel, đại lộ Champs-Élysées, nhà thờ Đức Bà và bảo tàng Louvre. Thành phố này quyến rũ không chỉ bởi kiến trúc cổ điển và nghệ thuật, mà còn bởi phong cách sống tinh tế, những quán cà phê thơ mộng và nền ẩm thực đỉnh cao. Một Paris lãng mạn, nghệ thuật và thanh lịch luôn làm say lòng du khách.', 'https://img.static-af.com/transform/45cb9a13-b167-4842-8ea8-05d0cc7a4d04/', '', '', '6/3/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Paris&output=embed\"></iframe></div><a href=\"http://aiyoutubetitlegenerator.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aiyoutubetitlegenerator.com</a></div>', 'https://img.static-af.com/transform/45cb9a13-b167-4842-8ea8-05d0cc7a4d04/', 'paris'),
(22, 'Vienna', 'Áo', 'Thủ đô nước Áo là nơi sản sinh những thiên tài âm nhạc như Mozart, Beethoven và Schubert. Vienna nổi bật với cung điện Schönbrunn, Nhà hát Opera quốc gia và các quán cà phê lịch sử lâu đời. Đây là điểm đến lý tưởng cho những ai yêu nghệ thuật, văn hóa và sự tinh tế trong từng chi tiết nhỏ.', 'https://awaytothecity.com/wp-content/uploads/2024/09/Austria-Vienna-Cityscape-with-St-Stephens-Cathedral_Cover.webp', '', '', '7/8/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Vienna&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://res.klook.com/images/fl_lossy.progressive,q_65/c_fill,w_1200,h_630/w_80,x_15,y_15,g_south_west,l_Klook_water_br_trans_yhcmh3/activities/uztbdmn0iu506yaxrywj/%C4%90%E1%BA%AFm%20ch%C3%ACm%20trong%20Ph%E1%BB%91%20c%E1%BB%95%20Vienna%3A%20Tour%20%C4%91i%20b%E1%BB%99%20l%E1%BB%8Bch%20s%E1%BB%AD%20v%C3%A0%20v%C4%83n%20h%C3%B3a.jpg', 'vienna'),
(23, 'Barcelona', 'Tây Ban Nha', 'Barcelona gây ấn tượng với kiến trúc độc đáo như nhà thờ Sagrada Família, công viên Güell và những con phố sống động ở khu Gothic. Với khí hậu dễ chịu, bãi biển đẹp, văn hóa Catalan đặc sắc và bóng đá cuồng nhiệt, Barcelona là nơi hội tụ giữa nghệ thuật, năng lượng và phong cách sống Địa Trung Hải.', 'https://www.broadwaytravel.com/blog/wp-content/uploads/2019/06/AdobeStock_211230289-1200x700.jpg', '', '', '4/29/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Barcelona+Tay+Ban+Nha&output=embed\"></iframe></div><a href=\"http://aiyoutubetitlegenerator.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aiyoutubetitlegenerator.com</a></div>', 'https://cdn-acn.watchity.net/acn/images/2a9c5338-6daa-427b-aa7a-c3f1aa488193/4e27b3a3-0263-437d-8ffb-ddb498455bbd/4e27b3a3-0263-437d-8ffb-ddb498455bbd_medium.jpeg', 'barcelona'),
(24, 'Santorini', 'Hy Lạp', 'Nằm ở Hy Lạp, Santorini là hòn đảo nổi tiếng với những ngôi nhà sơn trắng, mái vòm xanh nổi bật trên vách đá hướng ra biển xanh biếc. Đây là một trong những điểm đến lãng mạn nhất thế giới, lý tưởng cho tuần trăng mật, ngắm hoàng hôn tại Oia, và thưởng thức rượu vang địa phương trong khung cảnh ngoạn mục.', 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0a/40/6a/3c.jpg', '', '', '4/27/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Santorini+Hy+Lap&output=embed\"></iframe></div><a href=\"https://viralnado.net/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">viralnado.net</a></div>', 'https://media.cntraveller.com/photos/64e31fff3c56448b259aacdb/1:1/w_2644,h_2644,c_limit/santoriniGettyImages-528893342.jpeg', 'santorini'),
(25, 'Reykjavik', 'Iceland', 'Thủ đô nhỏ bé của Iceland là điểm khởi đầu tuyệt vời cho hành trình đến với các kỳ quan thiên nhiên như suối nước nóng Blue Lagoon, cực quang Bắc Cực, thác Gullfoss hay sông băng Vatnajökull. Reykjavik mang vẻ đẹp giản dị, yên bình nhưng hiện đại – nơi lý tưởng cho những ai yêu thiên nhiên và thích trải nghiệm độc đáo.', 'https://lp-cms-production.imgix.net/2024-06/GettyImages-661798951.jpeg?auto=compress&format=auto&fit=crop&q=50&w=1200&h=800', '', '', '5/16/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Reykjavik&output=embed\"></iframe></div><a href=\"https://viralnado.net/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">viralnado.net</a></div>', 'https://content.icelandtravel.is/wp-content/uploads/2019/03/Reykjavik.jpg', 'reykjavik'),
(26, 'Rome', 'Ý', 'Thành phố vĩnh cửu Rome là nơi lưu giữ những dấu tích vĩ đại của đế chế La Mã: Đấu trường Colosseum, Đền Pantheon, Đài phun nước Trevi, và Vatican – quốc gia nhỏ nhất thế giới. Dạo bước trên những con đường lát đá cổ kính, bạn như được quay ngược thời gian để sống trong lịch sử.', 'https://i.natgeofe.com/k/a6c9f195-de20-445d-9d36-745ef56042c5/OG_Colosseum_Ancient-Rome_KIDS_1122_3x2.jpg', '', '', '6/16/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Rome&output=embed\"></iframe></div><a href=\"https://embedcodesgenerator.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embedcodesgenerator.com</a></div>', 'https://img.static-kl.com/images/media/5A8A006F-0618-4245-BBC88553D651B6E2', 'rome'),
(27, 'Bonn', 'Đức', 'Nằm bên bờ sông Rhine, Bonn là quê hương của Beethoven và từng là thủ đô cũ của Tây Đức. Thành phố mang vẻ đẹp yên bình, kết hợp hài hòa giữa nét cổ kính và không khí học thuật hiện đại. Ghé thăm nhà Beethoven, dạo quanh khu phố cổ hoặc ngắm hoa anh đào rực rỡ vào mùa xuân sẽ mang lại trải nghiệm đáng nhớ.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/General_view_over_bonn_%28cropped%29.jpg/1200px-General_view_over_bonn_%28cropped%29.jpg', '', '', '6/11/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Bonn&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjeyuHuoZzvpS_seBynt0TSqR1JVSbK9mk_3zT18_f-A&s&ec=72940543', 'bonn'),
(28, 'Amsterdam', 'Hà Lan', 'Thủ đô Hà Lan là thiên đường cho những tâm hồn yêu nghệ thuật, văn hóa và phong cách sống phóng khoáng. Với hệ thống kênh đào chằng chịt, những ngôi nhà cổ kính, bảo tàng Van Gogh, Rijksmuseum và các quán cà phê độc đáo, Amsterdam là nơi bạn có thể vừa thong dong đạp xe, vừa đắm chìm trong nghệ thuật và tự do cá nhân.', 'https://lp-cms-production.imgix.net/2025-03/GettyImages-1495422795-16.9.jpg', '', '', '6/22/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Amsterdam&output=embed\"></iframe></div><a href=\"https://aitohumanizetextconverter.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aitohumanizetextconverter.com</a></div>', 'https://img.static-kl.com/images/media/5444C1BF-7D85-4DE4-A0CF823E2866C03F', 'amsterdam'),
(29, 'Umea', 'Thụy Điển', 'Nằm ở miền bắc Thụy Điển, Umeå là thành phố nhỏ nhưng có đời sống văn hóa và sáng tạo năng động. Được mệnh danh là \"Thành phố Văn hóa châu Âu\" năm 2014, nơi đây nổi bật với thiên nhiên tuyệt đẹp, các lễ hội nghệ thuật và không gian sống hài hòa với môi trường. Lý tưởng cho những ai muốn rời xa sự ồn ào và khám phá Bắc Âu đích thực.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9iyWATZqJ-y5kQ46DaO560jK84cnNZieKrw&s', '', '', '7/11/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Umea&output=embed\"></iframe></div><a href=\"https://aitohumanizetextconverter.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aitohumanizetextconverter.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2dcP2pHpV-aY9UEP2FdngLC04HlbUxN_3KomBmcy0ow&s&ec=72940543', 'umea'),
(30, 'Bruges', 'Bỉ', 'Bruges là một thành phố như bước ra từ truyện cổ tích với các con kênh thơ mộng, những con đường lát đá cuội, nhà thờ cổ kính và tháp chuông uy nghi. Được UNESCO công nhận là Di sản thế giới, Bruges là nơi hoàn hảo cho những buổi dạo chơi lãng mạn, thưởng thức socola, bia thủ công và nghệ thuật thời Trung cổ.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGDlv84plXUMrUFyy6LymKiJ6LOwfeNHcVMg&s', '', '', '7/18/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Bruges&output=embed\"></iframe></div><a href=\"https://aitohumanizetextconverter.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">aitohumanizetextconverter.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk2bCs2Ly9mzHfTpBr-oajzjTc0FtaXJgGPXXUAkAZxg&s&ec=72940543', 'bruges'),
(31, 'Machu Picchu', 'Peru', 'Ẩn mình trên dãy Andes của Peru, Machu Picchu là một trong những kỳ quan cổ đại bí ẩn và kỳ vĩ nhất thế giới. Với kiến trúc bằng đá ấn tượng nằm giữa núi rừng xanh thẳm, nơi đây từng là trung tâm văn hóa – tôn giáo của nền văn minh Inca. Chuyến leo núi đến Machu Picchu là hành trình tuyệt vời dành cho những người yêu lịch sử và phiêu lưu khám phá.', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQvFsGNoZT-hMaS_mORqdVw7SjMjrw0RH5PQ&s', '', '', '6/26/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Machu+Picchu&output=embed\"></iframe></div><a href=\"https://testosteronetherapy.org/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">testosteronetherapy.org</a></div>', 'https://upload.wikimedia.org/wikipedia/commons/b/bb/Machu_Picchu%2C_2023_%28012%29.jpg', 'machu-picchu'),
(32, 'Rio de Janeiro', 'Brazil', 'Nằm bên bờ Đại Tây Dương, Rio de Janeiro là một trong những thành phố nổi bật nhất Nam Mỹ với bãi biển Copacabana sôi động, tượng Chúa Cứu Thế khổng lồ trên đỉnh Corcovado và lễ hội Carnival rực rỡ sắc màu. Rio mang trong mình một năng lượng sôi động, nóng bỏng và hoang dã khó quên.', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/57/8a/a2/copacabana.jpg?w=900&h=500&s=1', '', '', '6/4/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Rio+de+Janeiro&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://www.pestana.com/en/destinos/south-america/brazil/rio-janeiro/_jcr_content/root/container/hero_banner/cmp-hero-banner__container__background-image.coreimg.jpeg/1733414709992/herobanner-region-rio-de-janeiro.jpeg', 'rio-de-janeiro'),
(33, 'Cape Town', 'Nam Phi', 'Cape Town của Nam Phi mê hoặc du khách bởi vẻ đẹp hoang sơ của thiên nhiên và sự giao thoa văn hóa độc đáo. Nổi bật với núi Bàn hùng vĩ, bãi biển Camps Bay quyến rũ và đảo Robben lịch sử, nơi giam giữ Nelson Mandela, thành phố là điểm đến lý tưởng cho cả nghỉ dưỡng lẫn tìm hiểu lịch sử – văn hóa.', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/10/2e/1e/cape-town.jpg?w=1200&h=700&s=1', '', '', '5/1/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Cape+Town&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://cdn.britannica.com/42/126842-050-0803BC41/Sea-Point-Cape-Town-SAf.jpg', 'cape-town'),
(34, 'New York', 'Mỹ', 'New York là trung tâm văn hóa, tài chính và nghệ thuật của thế giới. Từ tượng Nữ Thần Tự Do, công viên Central Park, Quảng trường Times Square đến Broadway sôi động, thành phố này luôn mang đến những trải nghiệm sôi động, đa sắc màu và không ngừng đổi mới. Mỗi góc phố đều có một câu chuyện thú vị đang chờ được kể.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/960px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg', '', '', '6/15/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=New+York&output=embed\"></iframe></div><a href=\"https://testosteronetherapy.org/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">testosteronetherapy.org</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiAqzstuKXpBqe0rP3YTqykhYaLxPBnHTe5G55tvbGxDQa0EGB3FEkRvZ8CrUw6xLA9Xk&usqp=CAU', 'new-york'),
(35, 'San Francisco', 'Mỹ', 'Với biểu tượng là cầu Cổng Vàng (Golden Gate Bridge), San Francisco nổi bật bởi khí hậu mát mẻ, văn hóa đa dạng và tinh thần đổi mới. Bạn có thể dạo chơi tại bến cảng Pier 39, ghé thăm nhà tù Alcatraz hay thưởng thức cà phê tại các quán nhỏ ven đồi. Thành phố còn là cái nôi của công nghệ, gần thung lũng Silicon sôi động.', 'https://cdn.britannica.com/13/77413-050-95217C0B/Golden-Gate-Bridge-San-Francisco.jpg', '', '', '5/7/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=San+Francisco&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Us-ca-sanfran-goldengate.jpg/640px-Us-ca-sanfran-goldengate.jpg', 'san-francisco'),
(36, 'Vancouver', 'Canada', 'Vancouver nằm giữa núi non và biển cả, là sự kết hợp hài hòa giữa thiên nhiên hùng vĩ và đời sống đô thị hiện đại. Với hệ thống công viên xanh mát như Stanley Park, các khu chợ sôi động như Granville Island và sự đa văn hóa trong ẩm thực, đây là điểm đến yêu thích của người mê du lịch, thể thao ngoài trời và khám phá đô thị sạch – xanh.', 'https://media.timeout.com/images/106148123/750/562/image.jpg', '', '', '7/6/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Vancouver&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://pantravel.vn/wp-content/uploads/2024/01/thanh-pho-dang-song-voi-nhieu-nguoi-muon-tim-kiem-vung-dat-moi.jpg', 'vancouver'),
(37, 'Quebec City', 'Canada', 'Quebec City nổi bật với phố cổ kiến trúc Pháp, những con đường lát đá cuội và lâu đài Frontenac lộng lẫy nhìn ra sông St. Lawrence. Không khí cổ kính, văn hóa Pháp-Canada đặc trưng và các lễ hội mùa đông đầy màu sắc biến nơi đây thành điểm đến độc đáo và lãng mạn bậc nhất Bắc Mỹ.', 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Quebec_City_Rue_St-Louis_2010.jpg', '', '', '4/24/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Quebec+City&output=embed\"></iframe></div><a href=\"https://mapembeds.com\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">mapembeds.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8Bi8CtK5SdbrJ57SR7B9IFCtCKu_9iqQih4OhM7vXkw&s&ec=72940543', 'quebec-city'),
(38, 'Sydney', 'Úc', 'Là biểu tượng của nước Úc, Sydney quyến rũ với nhà hát Opera hình con sò, cầu cảng Harbour Bridge và các bãi biển như Bondi sôi động. Thành phố mang đến không khí trẻ trung, năng động, lý tưởng cho cả nghỉ dưỡng, khám phá văn hóa và hoạt động ngoài trời quanh năm.', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/93/a7/be/sydney-opera-house.jpg?w=1200&h=1200&s=1', '', '', '5/22/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Sydney&output=embed\"></iframe></div><a href=\"https://eatcolumbus.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">eatcolumbus.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSddK9_PrUukcuc3fYvRCNd--ojVxDaviH7ElVM24WL3A&s&ec=72940543', 'sydney'),
(39, 'Melbourne', 'Úc', 'Melbourne được biết đến là trung tâm nghệ thuật, thời trang và cà phê của nước Úc. Với những con phố đầy màu sắc nghệ thuật đường phố, các nhà hát, bảo tàng, lễ hội sôi động và ẩm thực đa dạng, thành phố này phù hợp cho du khách yêu thích sự sáng tạo, nhịp sống hiện đại và phong cách sống tinh tế.', 'https://upload.wikimedia.org/wikipedia/commons/4/46/Melburnian_Skyline_b.jpg', '', '', '5/3/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Melbourne&output=embed\"></iframe></div><a href=\"https://mapembeds.com\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">mapembeds.com</a></div>', 'https://cdn.britannica.com/64/190464-050-B74E1FD9/view-central-business-district-Melbourne-train-station.jpg', 'melbourne'),
(40, 'Wellington', 'New Zealand', 'Thủ đô nhỏ nhưng đầy cá tính của New Zealand, Wellington nằm giữa biển và núi, nổi bật với không gian nghệ thuật đậm chất đương đại, quán cà phê độc đáo và bảo tàng Te Papa hiện đại. Đây cũng là điểm đến yêu thích của người yêu phim ảnh, bởi là bối cảnh trong nhiều cảnh quay của loạt phim \"Chúa tể những chiếc nhẫn\". Gió mạnh – nhưng đầy cuốn hút.', 'https://wellingtonnz.bynder.com/transform/a2babfe9-9456-4806-a2d6-629f381f00fd/Cable-Car-02', '', '', '7/3/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Wellington&output=embed\"></iframe></div><a href=\"https://mapembeds.com\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">mapembeds.com</a></div>', 'https://bestour.com.vn/uploads/thu-do-WELLINGTON-new-zealand.jpg', 'wellington');
INSERT INTO `destinations` (`destination_id`, `name`, `country`, `description`, `image_url`, `section_1`, `section_2`, `best_time_to_visit`, `map_embed`, `image_gallery`, `slug`) VALUES
(41, 'Dubai', 'UAE', 'Dubai là một biểu tượng của sự xa hoa, phát triển và sáng tạo không giới hạn. Từ tòa tháp Burj Khalifa cao nhất thế giới, trung tâm thương mại Dubai Mall đến các khách sạn xa xỉ, đảo nhân tạo và sa mạc trải dài, thành phố này là minh chứng sống động cho cách con người có thể biến điều không thể thành hiện thực. Đến Dubai là trải nghiệm đỉnh cao của sự hiện đại.', 'https://vlink.vn/wp-content/uploads/2025/02/Du-lich-Dubai-thang-11-1.jpg', '', '', '6/7/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Dubai&output=embed\"></iframe></div><a href=\"https://eatcolumbus.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">eatcolumbus.com</a></div>', 'https://cdn.britannica.com/15/189715-050-4310222B/Dubai-United-Arab-Emirates-Burj-Khalifa-top.jpg', 'dubai'),
(42, 'Cairo', 'Ai Cập', 'Thủ đô của Ai Cập là điểm đến không thể bỏ qua với những di sản cổ đại như kim tự tháp Giza, tượng Nhân sư huyền thoại và bảo tàng Cairo lưu giữ xác ướp và kho báu của các vị Pharaoh. Cairo là nơi bạn có thể sống lại thời đại huy hoàng của nền văn minh Ai Cập cổ đại – một chuyến du hành xuyên thời gian thực thụ.', 'https://www.magnificenttravel.com/public/uploads/2025/01/26/67965360b48af/Cairo-Sultan-Hassan-Mosque--.jpg', '', '', '6/4/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Cairo&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2Dqr2FGOhnVytE5-oSu_YOgVPFuCCDuwOl9YZLrHIkAL1AhYphoUJAfOC8WVwAEr8T64&usqp=CAU', 'cairo'),
(43, 'Istanbul', 'Thổ Nhĩ Kỳ', 'Là thành phố duy nhất trên thế giới nằm giữa châu Á và châu Âu, Istanbul mang trong mình nét văn hóa Đông – Tây giao thoa tuyệt vời. Những công trình như Hagia Sophia, Nhà thờ Xanh (Blue Mosque), cung điện Topkapi và các khu chợ cổ Grand Bazaar tạo nên một bức tranh lịch sử, nghệ thuật và tôn giáo độc đáo. Thành phố này là một hành trình xuyên văn hóa.', 'https://cdn.britannica.com/58/93158-050-7719EB2B/view-Blue-Mosque-Istanbul-Hagia-Sophia.jpg', '', '', '4/26/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Istanbul&output=embed\"></iframe></div><a href=\"https://embeddablemap.com/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">embeddablemap.com</a></div>', 'https://a.travel-assets.com/findyours-php/viewfinder/images/res70/554000/554028-istanbul.jpg', 'istanbul'),
(44, 'Petra', 'Jordan', 'Ẩn mình giữa sa mạc, Petra là kỳ quan kiến trúc được khắc hoàn toàn trong đá với tuổi đời hơn 2.000 năm. “Kho báu” Al-Khazneh, hẻm núi Siq hẹp dài và các công trình cổ đại đã biến nơi đây thành một di sản thế giới kỳ bí, được mệnh danh là \"thành phố đã mất của người Nabatean\". Một điểm đến ngoạn mục và khác biệt.', 'https://topviettravel.com/wp-content/uploads/2023/02/Petra-Jordan.jpg', '', '', '5/25/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Petra&output=embed\"></iframe></div><a href=\"https://testosteronetherapy.org/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">testosteronetherapy.org</a></div>', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkz3mdoXSF364IZd8TXf-wCrax-B6vk1hTf2_z-RJGqA&s&ec=72940543', 'petra'),
(45, 'Moscow', 'Nga', 'Moscow lộng lẫy với quảng trường Đỏ, nhà thờ Saint Basil nhiều màu sắc, cung điện Kremlin và hệ thống tàu điện ngầm đẹp như cung điện. Đây là thành phố mang đậm dấu ấn lịch sử Nga hoàng, thời Liên Xô và sự phát triển hiện đại. Mỗi bước đi ở Moscow đều là một hành trình qua những chương sử hào hùng.', 'https://geohistory.today/wp-content/uploads/2017/09/Moscow.jpg', '', '', '5/23/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Moscow&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://cdn.britannica.com/83/84883-050-053834E9/Red-Square-Moscow.jpg', 'moscow'),
(46, 'Prague', 'Cộng hòa Séc', 'Thủ đô Cộng hòa Séc được mệnh danh là “thành phố của trăm ngọn tháp” với lâu đài Prague, cầu Charles, đồng hồ thiên văn và các khu phố cổ quyến rũ. Không gian vừa huyền bí, vừa lãng mạn, đầy chất thơ khiến Prague trở thành một trong những thành phố đẹp nhất châu Âu dành cho người mê lịch sử và kiến trúc Gothic.', 'https://statemag.state.gov/wp-content/uploads/2023/10/1123pom-3-1.jpg', '', '', '7/11/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Prague&output=embed\"></iframe></div><a href=\"https://mapembeds.com\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">mapembeds.com</a></div>', 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0b/e1/1b/2c.jpg', 'prague'),
(47, 'Budapest', 'Hungary', 'Budapest là sự kết hợp hoàn hảo giữa cổ kính và hiện đại, với các công trình như tòa nhà Quốc hội Hungary, lâu đài Buda, cầu Chain và hệ thống suối nước nóng. Được mệnh danh là “Paris của Đông Âu”, Budapest quyến rũ du khách bởi vẻ đẹp lãng mạn, văn hóa đặc sắc và nhịp sống sôi động về đêm.', 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/36/37/32/caption.jpg?w=1100&h=1100&s=1', '', '', '5/24/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Budapest&output=embed\"></iframe></div><a href=\"https://viralnado.net/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">viralnado.net</a></div>', 'https://www.agoda.com/wp-content/uploads/2024/08/Budapest-Hungary-Featured-Image.jpg', 'budapest'),
(48, 'Warsaw', 'Ba Lan', 'Thủ đô của Ba Lan là biểu tượng của sự kiên cường và tái sinh. Sau Thế chiến II, Warsaw đã được phục dựng gần như nguyên vẹn với khu phố cổ, cung điện văn hóa – khoa học và các bảo tàng lịch sử sâu sắc. Đây là điểm đến đáng giá cho những ai muốn tìm hiểu lịch sử châu Âu hiện đại và sự sống dậy đầy cảm hứng.', 'https://www.lot.com/content/dam/lot/lot-com/destination-photos/polska/warsaw/warsaw10.coreimg.jpg/1729774206001/warsaw10.jpg', '', '', '5/5/2025', '<div style=\"position: relative;\"><div style=\"position: relative; padding-bottom: 75%; height: 0; overflow: hidden;\"><iframe style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" loading=\"lazy\" allowfullscreen src=\"https://maps.google.com/maps?q=Warsaw&output=embed\"></iframe></div><a href=\"https://tariffcalculator.us/\" rel=\"noopener\" target=\"_blank\" style=\"position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0;\">tariffcalculator.us</a></div>', 'https://www.arup.com/globalassets/images/projects/w/warsaw-green-city-climate-and-action-plan/view-of-city-of-warsaw-teaser.jpg', 'warsaw');

-- --------------------------------------------------------

--
-- Table structure for table `tours`
--

CREATE TABLE `tours` (
  `tour_id` int(11) NOT NULL,
  `destination_id` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text DEFAULT NULL,
  `duration` varchar(50) DEFAULT NULL,
  `pax` int(11) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `image_url` varchar(255) DEFAULT NULL,
  `rating` float DEFAULT NULL,
  `reviews` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tours`
--

INSERT INTO `tours` (`tour_id`, `destination_id`, `name`, `description`, `duration`, `pax`, `location`, `price`, `image_url`, `rating`, `reviews`) VALUES
(2, 2, 'Côn Đảo', 'Quần đảo hoang sơ nổi tiếng với nhà tù lịch sử và bãi biển tuyệt đẹp.', '2 ngày 1 đêm', 6, 'Việt Nam', 8000000.00, 'https://media-cdn.tripadvisor.com/media/photo-s/29/b5/44/c4/six-senses-con-dao.jpg', 4.9, 399),
(3, 3, 'Đà Nẵng - Hội An', 'Thành phố hiện đại kết hợp với phố cổ yên bình, đèn lồng và kiến trúc cổ.', '3 ngày 2 đêm', 8, 'Việt Nam', 7000000.00, 'https://i2.ex-cdn.com/crystalbay.com/files/content/2024/11/01/di-da-nang-hoi-an-nen-di-may-ngay-3-0926.jpg', 4.6, 166),
(4, 4, 'Cố đô Huế', 'Kinh đô xưa của triều Nguyễn, nổi bật với Đại Nội và các lăng tẩm vua chúa.', '4 ngày 3 đêm', 7, 'Việt Nam', 5000000.00, 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Ngomon2.jpg', 4.3, 245),
(5, 5, 'Phú Quốc', 'Đảo ngọc của Việt Nam với biển xanh, cát trắng và hệ sinh thái đa dạng.', '3 ngày 2 đêm', 6, 'Việt Nam', 8500000.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjZWhRT0vwzWahfmPQgwKG7Cf05jaEurlPcQ&s', 4.8, 436),
(6, 6, 'Hang Sơn Đoòng', 'Hang động lớn nhất thế giới với hệ sinh thái riêng biệt và kỳ quan thiên nhiên.', '5 ngày 4 đêm', 8, 'Việt Nam', 70000000.00, 'https://thanhnien.mediacdn.vn/Uploaded/phucndh/2022_04_14/a4-5211.jpg', 5, 708),
(7, 7, 'Ninh Bình', 'Vịnh Hạ Long trên cạn với Tràng An, Tam Cốc và hang động đá vôi kỳ vĩ.', '3 ngày 2 đêm', 1, 'Việt Nam', 4000000.00, 'https://thungnham.com/wp-content/uploads/2024/03/khu-du-lich-trang-an-2.webp', 4.7, 141),
(8, 8, 'Bãi Cát Bà', 'Quần đảo nằm gần Hạ Long với rừng quốc gia và bãi biển tuyệt đẹp.', '3 ngày 2 đêm', 4, 'Việt Nam', 5000000.00, 'https://catbaexpress.com/upload/images/bai_bien_cat_co_cat_ba.jpg', 5, 155),
(9, 9, 'Thác Bản Giốc', 'Một trong những thác nước đẹp nhất Việt Nam nằm giữa biên giới Việt - Trung.', '4 ngày 3 đêm', 9, 'Việt Nam', 6000000.00, 'https://hanotour.com.vn/upload_images/images/thac_B%E1%BA%A3n_Gi%E1%BB%91c.jpg', 4.4, 452),
(10, 10, 'Tháp Bánh Ít', 'Di tích Chăm Pa cổ nổi tiếng tại Bình Định với kiến trúc đặc trưng.', '2 ngày 1 đêm', 8, 'Việt Nam', 3000000.00, 'https://binhdinh.gov.vn/upload/3005784/20220516/thap-banh-it-thap-chinh_79cc8_20eb8.jpg', 4.6, 183),
(11, 11, 'Siem Reap', 'Thành phố gần Angkor Wat - kỳ quan nổi tiếng của Campuchia.', '3 ngày 2 đêm', 8, 'Campuchia', 7000000.00, 'https://www.siemreap.net/wp-content/uploads/2017/12/siem-reap-pub-street-sunset.jpg', 4.8, 719),
(12, 12, 'Vạn Lý Trường Thành', 'Công trình phòng thủ vĩ đại kéo dài hàng ngàn cây số ở Trung Quốc.', '3 ngày 2 đêm', 4, 'Trung Quốc', 11000000.00, 'https://transviet.com.vn/images/Khuyen-Mai/Avatar/cam_nang_du_lich/great-wall-transviet3.png', 4.9, 554),
(13, 13, 'Kuala Lumpur', 'Thủ đô hiện đại của Malaysia với tháp đôi Petronas biểu tượng.', '3 ngày 2 đêm', 7, 'Malaysia', 7000000.00, 'https://lp-cms-production.imgix.net/2022-11/Malaysia-iStock-1344146598-RFE_1.jpeg?w=1095&fit=crop&crop=faces%2Cedges&auto=format&q=75', 4.2, 580),
(14, 14, 'Đền Taj Mahal', 'Lăng mộ bằng đá cẩm thạch trắng tuyệt đẹp - biểu tượng tình yêu ở Ấn Độ.', '4 ngày 3 đêm', 5, 'Ấn Độ', 6000000.00, 'https://mia.vn/media/uploads/blog-du-lich/di-tich-den-taj-mahal-an-do-02-1702374379.jpg', 4.5, 385),
(15, 15, 'Đảo Bali', 'Thiên đường nghỉ dưỡng của Indonesia với bãi biển và văn hóa đặc sắc.', '3 ngày 2 đêm', 7, 'Indonesia', 9000000.00, 'https://booking.pystravel.vn/uploads/posts/albums/5053/88c7a9338a57e980a3794612b8e6793f.jpg', 4.6, 242),
(16, 16, 'Chùa Shwedagon', 'Ngôi chùa Phật giáo linh thiêng nhất Myanmar với tháp vàng nổi bật.', '3 ngày 2 đêm', 2, 'Myanmar', 6000000.00, 'https://media.tuyenquangtv.vn/public/file/fb9e3a036ab59c2c016ac3618a0d3aec/old_image/uploaded/130/2017/1/4/030_chua-shwedagon-1.jpg', 4.3, 745),
(17, 17, 'Bangkok', 'Thủ đô sôi động của Thái Lan với cung điện hoàng gia và ẩm thực đường phố.', '2 ngày 1 đêm', 10, 'Thái Lan', 6500000.00, 'https://static.independent.co.uk/2025/01/03/14/newFile-12.jpg', 4.6, 586),
(18, 18, 'Thượng Hải - Bắc Kinh', 'Hai thành phố lớn nhất Trung Quốc, kết hợp hiện đại và truyền thống.', '3 ngày 2 đêm', 10, 'Trung Quốc', 15000000.00, 'https://cdn.saigontimestravel.com/storage/images/retail/wp-content/uploads/2024/02/Tour-Bac-Kinh-10.jpg', 4.8, 421),
(19, 19, 'Seoul', 'Trung tâm công nghệ, văn hóa Hàn Quốc với cung điện cổ và đời sống hiện đại.', '3 ngày 2 đêm', 6, 'Hàn Quốc', 12000000.00, 'https://static.independent.co.uk/2022/12/29/14/iStock-464629385.jpg?width=1200&height=900&fit=crop', 4.2, 631),
(20, 20, 'Tokyo', 'Thủ đô năng động của Nhật Bản, nổi tiếng với công nghệ và văn hóa đa dạng.', '5 ngày 4 đêm', 1, 'Nhật Bản', 18000000.00, 'https://plus.unsplash.com/premium_photo-1661914240950-b0124f20a5c1?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dG9reW98ZW58MHx8MHx8fDA%3D', 4.8, 573),
(21, 21, 'Paris', 'Kinh đô ánh sáng với tháp Eiffel và bảo tàng Louvre.', '4 ngày 3 đêm', 8, 'Pháp', 35000000.00, 'https://img.static-af.com/transform/45cb9a13-b167-4842-8ea8-05d0cc7a4d04/', 4.9, 669),
(22, 22, 'Vienna', 'Trung tâm âm nhạc cổ điển và kiến trúc baroque', '3 ngày 2 đêm', 1, 'Áo', 30000000.00, 'https://awaytothecity.com/wp-content/uploads/2024/09/Austria-Vienna-Cityscape-with-St-Stephens-Cathedral_Cover.webp', 4.2, 539),
(23, 23, 'Barcelona', 'Thành phố nghệ thuật với kiến trúc Gaudí', '3 ngày 2 đêm', 6, 'Tây Ban Nha', 28000000.00, 'https://www.broadwaytravel.com/blog/wp-content/uploads/2019/06/AdobeStock_211230289-1200x700.jpg', 4.3, 681),
(24, 24, 'Santorini', 'Hòn đảo trắng xanh tuyệt đẹp giữa Địa Trung Hải.', '2 ngày 1 đêm', 3, 'Hy Lạp', 33000000.00, 'https://media.tacdn.com/media/attractions-splice-spp-674x446/0a/40/6a/3c.jpg', 4.7, 721),
(25, 25, 'Reykjavik', 'Thủ đô gần Bắc Cực với cảnh quan thiên nhiên kỳ vĩ.', '4 ngày 3 đêm', 2, 'Iceland', 50000000.00, 'https://lp-cms-production.imgix.net/2024-06/GettyImages-661798951.jpeg?auto=compress&format=auto&fit=crop&q=50&w=1200&h=800', 4.9, 768),
(26, 26, 'Rome', '	Thành phố lịch sử với đấu trường Colosseum.', '3 ngày 2 đêm', 7, 'Ý', 30000000.00, 'https://i.natgeofe.com/k/a6c9f195-de20-445d-9d36-745ef56042c5/OG_Colosseum_Ancient-Rome_KIDS_1122_3x2.jpg', 4.8, 602),
(27, 27, 'Bonn', 'Thành phố lâu đời và cổ kính', '3 ngày 2 đêm', 1, 'Đức', 20000000.00, 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/General_view_over_bonn_%28cropped%29.jpg/1200px-General_view_over_bonn_%28cropped%29.jpg', 5, 733),
(28, 28, 'Amsterdam', 'Thành phố của kênh rạch và xe đạp nổi tiếng', '3 ngày 2 đêm', 8, 'Hà Lan', 32000000.00, 'https://lp-cms-production.imgix.net/2025-03/GettyImages-1495422795-16.9.jpg', 4.6, 525),
(29, 29, 'Umea', 'Thành phố của những cây bạch dương', '3 ngày 2 đêm', 1, 'Thụy Điển', 25000000.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9iyWATZqJ-y5kQ46DaO560jK84cnNZieKrw&s', 4.4, 350),
(30, 30, 'Bruges', 'Thành phố cổ xưa trên mặt nước', '4 ngày 3 đêm', 3, 'Bỉ', 30000000.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGDlv84plXUMrUFyy6LymKiJ6LOwfeNHcVMg&s', 4.8, 543),
(31, 31, 'Machu Picchu', 'Thành cổ Inca trên núi cao', '5 ngày 4 đêm', 9, 'Peru', 28000000.00, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQvFsGNoZT-hMaS_mORqdVw7SjMjrw0RH5PQ&s', 4.7, 447),
(32, 32, 'Rio de Janeiro', 'Thành phố nổi tiếng với tượng Chúa cứu thế', '2 ngày 1 đêm', 8, 'Brazil', 26000000.00, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/18/57/8a/a2/copacabana.jpg?w=900&h=500&s=1', 4.2, 146),
(33, 33, 'Cape Town', 'Thành phố bên bờ biển với núi Bàn nổi tiếng', '3 ngày 2 đêm', 8, 'Nam Phi', 24000000.00, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/10/2e/1e/cape-town.jpg?w=1200&h=700&s=1', 4.7, 421),
(34, 34, 'New York', 'Thành phố không ngủ với tượng Nữ thần Tự do', '3 ngày 2 đêm', 6, 'Mỹ', 35000000.00, 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg/960px-View_of_Empire_State_Building_from_Rockefeller_Center_New_York_City_dllu_%28cropped%29.jpg', 4.9, 246),
(35, 35, 'San Francisco', 'Cầu Cổng Vàng và phố dốc đặc trưng', '2 ngày 1 đêm', 3, 'Mỹ', 32000000.00, 'https://cdn.britannica.com/13/77413-050-95217C0B/Golden-Gate-Bridge-San-Francisco.jpg', 4.4, 442),
(36, 36, 'Vancouver', 'Thành phố biển với thiên nhiên tuyệt đẹp', '4 ngày 3 đêm', 1, 'Canada', 20000000.00, 'https://media.timeout.com/images/106148123/750/562/image.jpg', 4.5, 530),
(37, 37, 'Quebec City', 'Thành phố cổ châu Âu tại Bắc Mỹ', '3 ngày 2 đêm', 2, 'Canada', 18000000.00, 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Quebec_City_Rue_St-Louis_2010.jpg', 4.3, 385),
(38, 38, 'Sydney', 'Nhà hát con sò và cảng Sydney', '3 ngày 2 đêm', 1, 'Úc', 22000000.00, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/93/a7/be/sydney-opera-house.jpg?w=1200&h=1200&s=1', 4.6, 281),
(39, 39, 'Melbourne', 'Thành phố văn hóa của Úc', '5 ngày 4 đêm', 4, 'Úc', 19000000.00, 'https://upload.wikimedia.org/wikipedia/commons/4/46/Melburnian_Skyline_b.jpg', 5, 225),
(40, 40, 'Wellington', 'Thành phố yên bình và là trung tâm làm phim', '3 ngày 2 đêm', 6, 'New Zealand', 15000000.00, 'https://wellingtonnz.bynder.com/transform/a2babfe9-9456-4806-a2d6-629f381f00fd/Cable-Car-02', 4.4, 313),
(41, 41, 'Dubai', 'Thành phố của những tòa nhà chọc trời', '3 ngày 2 đêm', 5, 'UAE', 25000000.00, 'https://vlink.vn/wp-content/uploads/2025/02/Du-lich-Dubai-thang-11-1.jpg', 4.3, 650),
(42, 42, 'Cairo', 'Kim Tự Tháp Giza và Sông Nile', '4 ngày 3 đêm', 4, 'Ai Cập', 16000000.00, 'https://www.magnificenttravel.com/public/uploads/2025/01/26/67965360b48af/Cairo-Sultan-Hassan-Mosque--.jpg', 4.6, 456),
(43, 43, 'Istanbul', 'Giao điểm Á – Âu với lịch sử phong phú', '3 ngày 2 đêm', 4, 'Thổ Nhĩ Kỳ', 18000000.00, 'https://cdn.britannica.com/58/93158-050-7719EB2B/view-Blue-Mosque-Istanbul-Hagia-Sophia.jpg', 4.3, 150),
(44, 44, 'Petra', 'Thành phố đá đỏ cổ đại nổi tiếng', '3 ngày 2 đêm', 6, 'Jordan', 20000000.00, 'https://topviettravel.com/wp-content/uploads/2023/02/Petra-Jordan.jpg', 5, 325),
(45, 45, 'Moscow', 'Quảng trường Đỏ và điện Kremlin', '3 ngày 2 đêm', 5, 'Nga', 17000000.00, 'https://geohistory.today/wp-content/uploads/2017/09/Moscow.jpg', 4.7, 777),
(46, 46, 'Prague', 'Thành phố cổ kính với lâu đài Prague', '3 ngày 2 đêm', 4, 'Cộng hòa Séc', 15000000.00, 'https://statemag.state.gov/wp-content/uploads/2023/10/1123pom-3-1.jpg', 4.6, 315),
(47, 47, 'Budapest', 'Thành phố đôi bên dòng sông Danube', '3 ngày 2 đêm', 8, 'Hungary', 14000000.00, 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/36/37/32/caption.jpg?w=1100&h=1100&s=1', 4.2, 787),
(48, 48, 'Warsaw', 'Thành phố lịch sử được phục dựng sau chiến tranh', '4 ngày 3 đêm', 6, 'Ba Lan', 12000000.00, 'https://www.lot.com/content/dam/lot/lot-com/destination-photos/polska/warsaw/warsaw10.coreimg.jpg/1729774206001/warsaw10.jpg', 4.9, 736),
(49, 49, 'Oslo', 'Thủ đô yên bình với kiến trúc hiện đại và cổ điển', '3 ngày 2 đêm', 6, 'Na Uy', 22000000.00, 'https://res.cloudinary.com/gofjords-com/images/w_1024,h_640,c_scale/f_auto,q_auto:eco/v1700208495/Destinations/Oslo/Oslo-opera-house-waterfront-photo-Bob-Engelsen/Oslo-opera-house-waterfront-photo-Bob-Engelsen.jpg?_i=AA', 4.5, 541);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `user_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `user_role` int(11) NOT NULL DEFAULT 1 COMMENT '0=admin, 1=user',
  `phone` varchar(20) DEFAULT NULL,
  `id_card` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `name`, `email`, `password_hash`, `user_role`, `phone`, `id_card`) VALUES
(136, 'Dang Phan', 'haidangphan054@gmail.com', '$2y$10$Ff/z5u5d5nq7toPEP/D/IutZl8jTCtSva.wpGkPYDK8Wta48RCiGu', 0, '0889013678', '012345678901'),
(137, 'Dang Phan', 'haidangphan053@gmail.com', '$2y$10$d7yEbJRC0AB.z.LrApZ.4uqW4rXb8KpTIjO.umPTIyg5bQnlKFlT.', 2, '0889013678', '012345678901'),
(138, '1', 'user@1', '$2y$10$fuwKybE7In/bCrmBnyZfzeZtpNupBCr5/QKdCyTBszTVmVxrp.vOq', 1, '1', '123456789123');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bookings`
--
ALTER TABLE `bookings`
  ADD PRIMARY KEY (`booking_id`),
  ADD KEY `user_id` (`user_id`),
  ADD KEY `tour_id` (`tour_id`);

--
-- Indexes for table `contacts`
--
ALTER TABLE `contacts`
  ADD PRIMARY KEY (`contact_id`);

--
-- Indexes for table `destinations`
--
ALTER TABLE `destinations`
  ADD PRIMARY KEY (`destination_id`);

--
-- Indexes for table `tours`
--
ALTER TABLE `tours`
  ADD PRIMARY KEY (`tour_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`user_id`),
  ADD UNIQUE KEY `email` (`email`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `bookings`
--
ALTER TABLE `bookings`
  MODIFY `booking_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1117;

--
-- AUTO_INCREMENT for table `contacts`
--
ALTER TABLE `contacts`
  MODIFY `contact_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `destinations`
--
ALTER TABLE `destinations`
  MODIFY `destination_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=54;

--
-- AUTO_INCREMENT for table `tours`
--
ALTER TABLE `tours`
  MODIFY `tour_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=57;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=139;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `bookings`
--
ALTER TABLE `bookings`
  ADD CONSTRAINT `bookings_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`),
  ADD CONSTRAINT `bookings_ibfk_2` FOREIGN KEY (`tour_id`) REFERENCES `tours` (`tour_id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
